### ISSUE TITLE
Redirect to setup-config.php returns 404 Not Found

### ISSUE THREAD

**Issue by mcki0127** [amintado/yii2-module-wordpress#2]
The redirect to setup-config in wp-load, line 202 returns the error "404 Not Found."  Is this a configuration error on my end or an issue with the module?

I posted this same question on the Yii extensions forum: http://www.yiiframework.com/forum/index.php/topic/76425-amintadoyii2-module-wordpress/

**Comment by mcki0127** [comment]
I ended up configuring WordPress manually.  The module is returning "OK;Finished".  Now, how do I access WordPress?  I only get a 404 not found error because /cms is looking for site/cms.  I don't understand how WordPress is intended to function outside the frontend/web folder.  

If I can get this last step to work, this will be an awesome extension!

**Comment by srakl** [comment]
@mcki0127 how did you configure it? I'm getting a 404 error on `https://localhost/yii2/frontend/web/index.php?r=cms/wp-admin/setup-config.php`


```
yii\base\InvalidRouteException: Unable to resolve the request "cms/wp-admin/setup-config.php". in C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\base\Module.php:543
Stack trace:
#0 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\web\Application.php(104): yii\base\Module->runAction('cms/wp-admin/se...', Array)
#1 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 C:\xampp\htdocs\yii2\frontend\web\index.php(31): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\web\Application.php:116
Stack trace:
#0 C:\xampp\htdocs\yii2\vendor\yiisoft\yii2\base\Application.php(392): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 C:\xampp\htdocs\yii2\frontend\web\index.php(31): yii\base\Application->run()
#2 {main}
```

**Comment by mcki0127** [comment]
@srakl I abandoned this module and ended up installing Wordpress as a standalone application on a subdomain.   I think that was the better way to go rather than trying to fit Wordpress into Yii.

**Comment by srakl** [comment]
@mcki0127 so i could install it in frontend/web/WordPress? how would i get the content of, say, the "about us" page in wordpress and display it on a Yii view?

**Comment by mcki0127** [comment]
I'm not sure about the about page, but you should be able to query anything from the Wordpress database.  I created a frontend model with methods such as getPosts, getComments, etc.

```
public static function getComments($postIds)
{
	$query = (new \yii\db\Query());
	$query->select('COUNT(comment_id), comment_post_id')
		->from('comments')
		->where('comment_post_id IN(' . implode(',',$postIds) .')')
		->andWhere(['comment_approved' => 1])
		->groupBy('comment_post_id');
      $array = $query->all(\Yii::$app->dbblog);
		
    return ArrayHelper::index($array, 'comment_post_id');
}
```

**Comment by yiiman-dev** [comment]
Hi Friends
I Created this source very years ago
i not recommend integrate wordpress with Yii now.
because wordpress is very slow now and it will be slower with this integrate.
but if you want it i should install and upgrade this source to work under new versions of wordpress
what you say ?

**Comment by mcki0127** [comment]
@amintado I don't need it myself as I'm already set up with a separate Wordpress install.  But thank you for your kind offer.
